# Generated by Django 4.2.13 on 2024-07-09 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Name of item to be delivered', max_length=255, verbose_name='Item Name')),
                ('item_type', models.CharField(choices=[('clothing', 'Clothing'), ('Food', 'Food'), ('documents', 'Documents'), ('pharmaceuticals', 'Pharmaceuticals'), ('electronics', 'Electronics'), ('goods', 'Goods')], default='goods', help_text='Select the type of item to be delivered', max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='small', help_text='Select the size of type to be delivered', max_length=20)),
                ('photo', models.ImageField(blank=True, default='static/images/photo.jpg', null=True, upload_to='media/delivery', verbose_name='Photo')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('pickup_in_progress', 'Pickup in progress'), ('in-progress', 'Delivery In Progress'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='creating', max_length=50)),
                ('pickup_address', models.CharField(max_length=255, null=True)),
                ('pickup_latitude', models.FloatField(default=0)),
                ('pickup_longitude', models.FloatField(default=0)),
                ('pickup_photo', models.ImageField(blank=True, default='static/images/pickup.jpg', null=True, upload_to='media/delivery/pickup', verbose_name='Pickup')),
                ('sender_name', models.CharField(help_text='Name of the sender or the person to be picked up from', max_length=255, null=True)),
                ('sender_phone', models.CharField(help_text='Phone number of the sender or the person to be picked up from', max_length=14, null=True)),
                ('delivery_address', models.CharField(max_length=255, null=True)),
                ('delivery_latitude', models.FloatField(default=0)),
                ('delivery_longitude', models.FloatField(default=0)),
                ('recipient_name', models.CharField(help_text='Name of the receiver or the person to be delivered to', max_length=255, null=True)),
                ('recipient_phone', models.CharField(help_text='Name of the receiver or the person to be delivered to', max_length=14, null=True)),
                ('delivery_photo', models.ImageField(blank=True, default='static/images/delivery.jpg', null=True, upload_to='media/delivery/delivery', verbose_name='Delivery')),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('pickedup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet Balance'), ('card', 'Card Payment'), ('cod', 'Cash on Delivery')], default='card', max_length=50)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_deliveries', to='accounts.courier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deliveries', to='accounts.customer')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid')], default='not_paid', max_length=50)),
                ('transaction_verified', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_transactions', to='shipments.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
