# Generated by Django 4.2.13 on 2024-07-03 05:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recipient_name',
            field=models.CharField(help_text='Name of the receiver or the person to be delivered to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Name of the receiver or the person to be delivered to', max_length=50, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sender_name',
            field=models.CharField(help_text='Name of the sender or the person to be picked up from', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sender_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the sender or the person to be picked up from', max_length=50, null=True, region=None),
        ),
    ]
