# Generated by Django 4.2.13 on 2024-07-03 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmethod',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_methods', to='shipments.delivery'),
        ),
    ]
