# Generated by Django 4.2.13 on 2024-07-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_transactionmethod_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='small', help_text='Select the size of type to be delivered', max_length=20),
        ),
    ]
