# Generated by Django 4.2.13 on 2024-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='item_type',
            field=models.CharField(choices=[('Food', 'Food'), ('documents', 'Documents'), ('gadgets', 'Gadgets'), ('appliances', 'Appliances'), ('furniture', 'Furniture'), ('clothing_&_apparel', 'Clothing & Apparel'), ('health_&_beauty', 'Health & Beauty'), ('sports_&_outdoor', 'Sports & Outdoor'), ('beverages', 'Beverages'), ('office_supplies', 'Office Supplies'), ('electrical_&_industrial_equipments', 'Electrical & Industrial Equipments'), ('medical_supplies', 'Medical Supplies'), ('packaging_material', 'Packaging Material'), ('goods', 'Goods'), ('others', 'Others')], default='goods', help_text='Select the type of item to be delivered', max_length=50),
        ),
    ]
