# Generated by Django 4.2.13 on 2024-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_delivery_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytransaction',
            name='transaction_method',
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('cod', 'Cash on Delivery')], default='card', max_length=50),
        ),
        migrations.DeleteModel(
            name='TransactionMethod',
        ),
    ]
