# Generated by Django 4.2.13 on 2024-07-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_remove_deliverytransaction_transaction_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='description',
        ),
    ]
