# Generated by Django 4.2.13 on 2024-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_remove_delivery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
