# Generated by Django 4.2.13 on 2024-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_alter_delivery_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
