# Generated by Django 4.2.13 on 2024-07-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_alter_deliverytransaction_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet Balance'), ('card', 'Card Payment'), ('cod', 'Cash on Delivery')], default='card', max_length=50),
        ),
    ]
