# Generated by Django 4.2.13 on 2024-07-07 15:56

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_alter_delivery_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/deliveries/delivery.jpg', null=True, upload_to='images/delivery/delivery', verbose_name='Delivery'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/deliveries/photo.jpg', null=True, upload_to='images/delivery', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/deliveries/pickup.jpg', null=True, upload_to='images/delivery/pickup', verbose_name='Pickup'),
        ),
    ]
