# Generated by Django 4.2.13 on 2024-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_delivery_delivery_photo_delivery_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='recipient_phone',
            field=models.CharField(help_text='Name of the receiver or the person to be delivered to', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sender_phone',
            field=models.CharField(help_text='Phone number of the sender or the person to be picked up from', max_length=14, null=True),
        ),
    ]
