# Generated by Django 4.2.13 on 2024-07-09 06:34

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_alter_delivery_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='media/deliveries/delivery.jpg', null=True, upload_to='media/delivery/delivery', verbose_name='Delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='media/deliveries/photo.jpg', null=True, upload_to='media/delivery', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='media/deliveries/pickup.jpg', null=True, upload_to='media/delivery/pickup', verbose_name='Pickup'),
        ),
    ]
