# Generated by Django 4.2.13 on 2024-07-09 11:31

import deliveet.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('courier', 'Courier')], default='customer', help_text='Select the type of account you wish to create', max_length=10)),
                ('first_name', models.CharField(help_text='Type in your first name', max_length=255)),
                ('last_name', models.CharField(help_text='Type in your last name', max_length=255)),
                ('email', models.EmailField(help_text='Type in your email address', max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Type in your phone number', max_length=128, null=True, region=None, unique=True, validators=[deliveet.utils.validators.phone_number_validator])),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_courier', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'User Accounts',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('avatar', models.ImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to='images/profile', verbose_name='Image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Select your sex', max_length=10)),
                ('user', models.OneToOneField(limit_choices_to={'account_type': 'courier'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='courier_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('courier_latitude', models.FloatField(default=0.0)),
                ('courier_longitude', models.FloatField(default=0.0)),
                ('fcm_token', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('avatar', models.ImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to='images/profile', verbose_name='Image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Select your sex', max_length=10)),
                ('user', models.OneToOneField(limit_choices_to={'account_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_account', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
