# Generated by Django 4.2.13 on 2024-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to=''),
        ),
    ]
