# Generated by Django 4.2.13 on 2024-07-05 19:11

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/default/courier.jpg', null=True, upload_to='images/courier/profile', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courier',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
