# Generated by Django 4.2.13 on 2024-07-07 14:07

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courier_avatar_courier_courier_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to='images/profile', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/profile/avatar.jpg', null=True, upload_to='images/profile', verbose_name='Image'),
        ),
    ]
