# Generated by Django 4.2.13 on 2024-07-11 13:47

import deliveet.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_courier_avatar_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Type in your phone number', null=True, unique=True, validators=[deliveet.utils.validators.phone_number_validator]),
        ),
    ]
