# Generated by Django 4.2.13 on 2024-07-08 01:16

import deliveet.utils.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_avatar_alter_courier_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Type in your phone number', max_length=128, null=True, region=None, unique=True, validators=[deliveet.utils.validators.phone_number_validator]),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
